Traceback (most recent call last):
  File "C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\train_loops.py", line 125, in wandb_train_td3
    ep_loss_Q1, ep_loss_Q2, ep_loss_actor = td3.train(key_train, config.batch_size)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\model.py", line 64, in train
    buffer_out = self.buffer.sample(random.split(buffer_key, batch_size), batch_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\buffer.py", line 33, in sample
    jax.random.choice(rng, self.state, (batch_size,)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\jax\_src\random.py", line 626, in choice
    key, _ = _check_prng_key("choice", key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\jax\_src\random.py", line 101, in _check_prng_key
    raise ValueError(f"{name} accepts a single key, but was given a key array of"
ValueError: choice accepts a single key, but was given a key array of shape (256, 2) != (). Use jax.vmap for batching.
