2024-10-23 10:37:46,638 INFO    Thread-15 (_run_job):16388 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-23 10:37:46,639 INFO    Thread-15 (_run_job):16388 [wandb_setup.py:_flush():79] Configure stats pid to 16388
2024-10-23 10:37:46,639 INFO    Thread-15 (_run_job):16388 [wandb_setup.py:_flush():79] Loading settings from C:\Users\31614\.config\wandb\settings
2024-10-23 10:37:46,639 INFO    Thread-15 (_run_job):16388 [wandb_setup.py:_flush():79] Loading settings from C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\wandb\settings
2024-10-23 10:37:46,639 INFO    Thread-15 (_run_job):16388 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'project': 'Pendulum-TD3', 'entity': 'senna-renting-radboud-university', 'root_dir': 'C:\\Users\\31614\\Documents\\AI_course_stuff\\RLForaging Thesis\\RLForagingAgents\\RL-models\\TD3', 'run_id': 'ui90huyw', 'sweep_param_path': 'C:\\Users\\31614\\Documents\\AI_course_stuff\\RLForaging Thesis\\RLForagingAgents\\RL-models\\TD3\\wandb\\sweep-dayu773b\\config-ui90huyw.yaml', 'sweep_id': 'dayu773b'}
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_init.py:_log_setup():532] Logging user logs to C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\wandb\run-20241023_103746-ui90huyw\logs\debug.log
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_init.py:_log_setup():533] Logging internal logs to C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\wandb\run-20241023_103746-ui90huyw\logs\debug-internal.log
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_init.py:_jupyter_setup():478] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000255046CF800>
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_init.py:init():617] calling init triggers
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_init.py:init():624] wandb.init called with sweep_config: {'batch_size': 64, 'buffer_size': 50000, 'gamma': 0.99, 'lr_actor': 0.0003969222512367563, 'lr_critic': 0.0007240822247786249, 'max_length_episode': 200, 'noise_clip': 1.0431564629127033, 'num_episodes': 100, 'policy_interval': 2, 'sigma': 0.637834599841307, 'sigma_explore': 0.8517232385814552, 'tau': 0.0882533054107292, 'warmup_amount': 500}
config: {}
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_init.py:init():667] starting backend
2024-10-23 10:37:46,641 INFO    Thread-15 (_run_job):16388 [wandb_init.py:init():671] sending inform_init request
2024-10-23 10:37:46,649 INFO    Thread-15 (_run_job):16388 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-10-23 10:37:46,650 INFO    Thread-15 (_run_job):16388 [wandb_init.py:init():684] backend started and connected
2024-10-23 10:37:46,664 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_config_callback():1394] config_cb None None {'batch_size': 64, 'buffer_size': 50000, 'gamma': 0.99, 'lr_actor': 0.0003969222512367563, 'lr_critic': 0.0007240822247786249, 'max_length_episode': 200, 'noise_clip': 1.0431564629127033, 'num_episodes': 100, 'policy_interval': 2, 'sigma': 0.637834599841307, 'sigma_explore': 0.8517232385814552, 'tau': 0.0882533054107292, 'warmup_amount': 500}
2024-10-23 10:37:46,665 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_label_probe_notebook():1346] probe notebook
2024-10-23 10:37:46,666 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_label_probe_notebook():1356] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-10-23 10:37:46,666 INFO    Thread-15 (_run_job):16388 [wandb_init.py:init():779] updated telemetry
2024-10-23 10:37:46,698 INFO    Thread-15 (_run_job):16388 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-23 10:37:46,873 INFO    Thread-15 (_run_job):16388 [wandb_init.py:init():863] starting run threads in backend
2024-10-23 10:37:47,417 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_console_start():2465] atexit reg
2024-10-23 10:37:47,417 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_redirect():2313] redirect: wrap_raw
2024-10-23 10:37:47,417 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_redirect():2378] Wrapping output streams.
2024-10-23 10:37:47,417 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_redirect():2403] Redirects installed.
2024-10-23 10:37:47,418 INFO    Thread-15 (_run_job):16388 [wandb_init.py:init():907] run started, returning control to user process
2024-10-23 10:37:47,429 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_finish():2164] finishing run senna-renting-radboud-university/Pendulum-TD3/ui90huyw
2024-10-23 10:37:47,430 INFO    Thread-15 (_run_job):16388 [jupyter.py:save_history():459] not saving jupyter history
2024-10-23 10:37:47,430 INFO    Thread-15 (_run_job):16388 [jupyter.py:save_ipynb():387] not saving jupyter notebook
2024-10-23 10:37:47,430 INFO    Thread-15 (_run_job):16388 [wandb_init.py:_jupyter_teardown():460] cleaning up jupyter logic
2024-10-23 10:37:47,430 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_atexit_cleanup():2428] got exitcode: 1
2024-10-23 10:37:47,430 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_restore():2410] restore
2024-10-23 10:37:47,430 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_restore():2416] restore done
2024-10-23 10:37:48,141 WARNING MsgRouterThr:16388 [router.py:message_loop():77] message_loop has been closed
2024-10-23 10:37:48,444 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_restore():2410] restore
2024-10-23 10:37:48,444 INFO    Thread-15 (_run_job):16388 [wandb_run.py:_restore():2416] restore done
2024-10-23 10:37:48,444 ERROR   Thread-15 (_run_job):16388 [wandb_run.py:_atexit_cleanup():2449] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\train_loops.py", line 89, in wandb_train_td3
    action_max = env.action_space(env_params).high[0] # Might need to refine this to generalize better
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'float' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 2440, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 2682, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\wandb_run.py", line 2654, in _on_probe_exit
    handle = self._backend.interface.deliver_poll_exit()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\interface\interface.py", line 948, in deliver_poll_exit
    return self._deliver_poll_exit(poll_exit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 483, in _deliver_poll_exit
    return self._deliver_record(record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 452, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 455, in _deliver_record
    interface._publish(record)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 225, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 157, in send_server_request
    self._send_message(msg)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 132, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
