2024-10-23 16:16:07,806 INFO    Thread-14 (_run_job):17528 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-23 16:16:07,806 INFO    Thread-14 (_run_job):17528 [wandb_setup.py:_flush():79] Configure stats pid to 17528
2024-10-23 16:16:07,806 INFO    Thread-14 (_run_job):17528 [wandb_setup.py:_flush():79] Loading settings from C:\Users\31614\.config\wandb\settings
2024-10-23 16:16:07,806 INFO    Thread-14 (_run_job):17528 [wandb_setup.py:_flush():79] Loading settings from C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\wandb\settings
2024-10-23 16:16:07,806 INFO    Thread-14 (_run_job):17528 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'project': 'Pendulum-TD3', 'entity': 'senna-renting-radboud-university', 'root_dir': 'C:\\Users\\31614\\Documents\\AI_course_stuff\\RLForaging Thesis\\RLForagingAgents\\RL-models\\TD3', 'run_id': 'wxfks8gg', 'sweep_param_path': 'C:\\Users\\31614\\Documents\\AI_course_stuff\\RLForaging Thesis\\RLForagingAgents\\RL-models\\TD3\\wandb\\sweep-wua96xrj\\config-wxfks8gg.yaml', 'sweep_id': 'wua96xrj'}
2024-10-23 16:16:07,812 INFO    Thread-14 (_run_job):17528 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-23 16:16:07,812 INFO    Thread-14 (_run_job):17528 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-10-23 16:16:07,812 INFO    Thread-14 (_run_job):17528 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-23 16:16:07,813 INFO    Thread-14 (_run_job):17528 [wandb_init.py:_log_setup():532] Logging user logs to C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\wandb\run-20241023_161607-wxfks8gg\logs\debug.log
2024-10-23 16:16:07,813 INFO    Thread-14 (_run_job):17528 [wandb_init.py:_log_setup():533] Logging internal logs to C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\wandb\run-20241023_161607-wxfks8gg\logs\debug-internal.log
2024-10-23 16:16:07,813 INFO    Thread-14 (_run_job):17528 [wandb_init.py:_jupyter_setup():478] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000017C91E64F50>
2024-10-23 16:16:07,813 INFO    Thread-14 (_run_job):17528 [wandb_init.py:init():617] calling init triggers
2024-10-23 16:16:07,813 INFO    Thread-14 (_run_job):17528 [wandb_init.py:init():624] wandb.init called with sweep_config: {'batch_size': 256, 'buffer_size': 50000, 'gamma': 0.99, 'lr_actor': 0.00027780519575132764, 'lr_critic': 0.001016229044210123, 'max_length_episode': 200, 'noise_clip': 0.74535300685802, 'num_episodes': 100, 'policy_interval': 2, 'sigma': 0.6400297321519643, 'sigma_explore': 0.584020932758223, 'tau': 0.01744982502374113, 'warmup_amount': 100}
config: {}
2024-10-23 16:16:07,813 INFO    Thread-14 (_run_job):17528 [wandb_init.py:init():667] starting backend
2024-10-23 16:16:07,813 INFO    Thread-14 (_run_job):17528 [wandb_init.py:init():671] sending inform_init request
2024-10-23 16:16:07,824 ERROR   Thread-14 (_run_job):17528 [wandb_init.py:init():1262] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 1252, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\wandb_init.py", line 672, in init
    service.inform_init(
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\service_connection.py", line 144, in inform_init
    self._client.send(inform_init=request)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 215, in send
    self.send_server_request(server_req)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 157, in send_server_request
    self._send_message(msg)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\31614\anaconda3\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 132, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
